/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package takeaway.challenge;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;

public class AppTest {
    @Test public void GetsNameAndPrice() {
        Dish Pierogi = new Dish("Pierogi", 3.99);
        assertEquals("returns the name", String.valueOf("Pierogi"), Pierogi.getName());
        assertEquals("returns the price", Double.valueOf(3.99), Pierogi.getPrice());
    }

    @Test public void AddsDishesToMenu() {
        Menu Menu = new Menu();
        Dish Pierogi = new Dish("Pierogi", 3.99);
        Menu.addDish(Pierogi);
        ArrayList<Dish> TestMenu = new ArrayList<Dish>();
        TestMenu.add(Pierogi);
        assertEquals("returns the menu with two dishes", TestMenu, Menu.getMenu());
    }

    @Test public void AddsDishesToOrder() {
        Dish Pierogi = new Dish("Pierogi", 3.99);
        Order Order = new Order();
        Order.AddToOrder(Pierogi);
        ArrayList<Dish> TestOrder = new ArrayList<Dish>();
        TestOrder.add(Pierogi);
        assertEquals("returns the order with one dish", TestOrder, Order.ViewOrder());
    }

    @Test public void ChecksOrderPrice() {
        Dish Pierogi = new Dish("Pierogi", 3.99);
        Dish Pizza = new Dish("Pizza", 5.50);
        Order Order = new Order();
        Order.AddToOrder(Pierogi);
        Order.AddToOrder(Pizza);
        assertTrue("Order price is 9.49", Order.CheckPrice(9.49));
        assertFalse("Order price is not 10.00", Order.CheckPrice(10.00));
    }
}